import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

const roboto = Roboto({  
  subsets: ["latin"],
});



export const metadata = {
  title: "Life Lesson",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${roboto.className} light h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        
        
        <main>{children}</main>
        <Footer />
        <ToastContainer />
        </body>
    </html>
  );
}
